[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rec-nn-mrept"
version = "0.1.0"
description = "Reconstruction Error Compensation Neural Network for MREPT"
readme = "README.md"
requires-python = ">=3.9,<3.10"
license = {text = "MIT"}
dependencies = [
    "numpy==1.24.3",
    "scikit-image==0.21.0",
    "torch==1.12.1",
]

[tool.setuptools.packages.find]
where = ["src"]
